# tasks file
---
- name: install | dependencies | fail
  ansible.builtin.apt:
    name: "{{ chrome_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  failed_when: false
  tags:
    - chrome-install-dependencies

- name: install | dependencies | fix
  ansible.builtin.lineinfile:
    dest: /etc/default/google-chrome
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^repo_add_once='
      line: 'repo_add_once="true"'
    - regexp: '^repo_reenable_on_distupgrade='
      line: 'repo_reenable_on_distupgrade="false"'
  tags:
    - chrome-install-dependencies
    - chrome-install-dependencies-fix

- name: install | dependencies | fix
  ansible.builtin.lineinfile:
    dest: "{{ chrome_sources_list_d_file }}"
    regexp: '(?i)^(deb.*)'
    line: '# \1'
    backrefs: true
    state: present
  failed_when: false
  tags:
    - chrome-install-dependencies
    - chrome-install-dependencies-fix

- name: install | dependencies | fix
  ansible.builtin.cron:
    name: google-chrome-remove-cron-daily
    job: >
      rm -f {{ chrome_cron_daily_file }} {{ chrome_sources_list_d_file }}
    minute: '*/5'
    cron_file: google-chrome-fix
    user: root
  tags:
    - chrome-install-dependencies
    - chrome-install-dependencies-fix

- name: install | dependencies | succeed
  ansible.builtin.apt:
    name: "{{ chrome_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - chrome-install-dependencies
