# tasks file
---
- name: install | copy
  ansible.builtin.copy:
    src: "{{ chrome_etc_default_file.lstrip('/') }}"
    dest: "{{ chrome_etc_default_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - chrome-install-copy

- name: install | dependencies | fail
  ansible.builtin.apt:
    name: "{{ chrome_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  ignore_errors: true
  tags:
    - chrome-install-dependencies

- name: install | dependencies | debug
  ansible.builtin.shell: >
    cat /etc/apt/sources.list.d/google-chrome.list
  register: _cat
  changed_when: false
  tags:
    - chrome-install-copy

- name: install | dependencies | fix
  ansible.builtin.lineinfile:
    dest: /etc/apt/sources.list.d/google-chrome.list
    regexp: '(?i)^(deb.*)'
    line: '# \1'
    backrefs: true
    state: present
  tags:
    - chrome-install-copy

- name: install | dependencies | debug
  ansible.builtin.shell: >
    cat /etc/apt/sources.list.d/google-chrome.list
  register: _cat
  changed_when: false
  tags:
    - chrome-install-copy

- name: install | dependencies | succeed
  ansible.builtin.apt:
    name: "{{ chrome_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - chrome-install-dependencies
