# tasks file
---
- name: install | copy
  ansible.builtin.copy:
    src: "{{ chrome_etc_default_file.lstrip('/') }}"
    dest: "{{ chrome_etc_default_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - chrome-install-copy

- name: install | copy
  ansible.builtin.copy:
    content: ''
    dest: /etc/apt/sources.list.d/google-chrome.list
    force: false
    mode: 0000
  tags:
    - chrome-install-copy

- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ chrome_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - chrome-install-dependencies
