# tasks file for chrome
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ chrome_dependencies }}"
  tags:
    - chrome-install-dependencies
