# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - chrome
    - chrome-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - chrome
    - chrome-install
