# tasks file
---
- ansible.builtin.include: repository.yml
  tags:
    - configuration
    - chrome
    - chrome-repository

- ansible.builtin.include: install.yml
  tags:
    - configuration
    - chrome
    - chrome-install
