# tasks file
---
- name: repository | install dependencies (pre)
  ansible.builtin.apt:
    name: "{{ chrome_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - chrome-repository-install-dependencies

- name: repository | (keyrings) directory | create
  ansible.builtin.file:
    path: "{{ chrome_keyring_dst | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - chrome-repository-keyrings-directory-create

- name: repository | (keyring) file | download  # noqa command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: >
    wget -O- {{ chrome_keyring_src }} | gpg --dearmor | tee {{ chrome_keyring_dst }} > /dev/null
  args:
    creates: "{{ chrome_keyring_dst }}"
  tags:
    - chrome-repository-keyring-file-download

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
    mode: 0644
  with_items: "{{ chrome_repositories }}"
  tags:
    - chrome-repository-add
