# tasks file
---
- name: repository | dependencies
  ansible.builtin.apt:
    name: "{{ chrome_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - chrome-repository-dependencies

- name: repository | add public key
  ansible.builtin.apt_key:
    id: A040830F7FAC5991
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  tags:
    - chrome-repository-public-key

- name: repository | add chrome repository
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ chrome_repositories }}"
  tags:
    - chrome-repository-add
